# First Workflow

name: learn-github-actions

run-name: $${{ github.actor }} is learning GitHub Actions

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: Who to greet in the log
        required: true
        default: 'World'
        type: string

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 first-job:
   runs-on: ubuntu-latest
   steps:
     - name: first-step
       shell: bash
       run: echo "hello world from github"
     - name: Print to Log
       id: print-to-log
       uses: actions/hello-world-javascript-action@main
       with:
         who-to-greet: ${{ inputs.who-to-greet }}

