# First Workflow

name: advanced-workflow

env:
  WORKFLOW_VAR: "This variable is declared at the workflow level"

run-name: Advanced workflow

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: Who to greet in the log
        required: true
        default: 'World'
        type: string

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 first-job:
   runs-on: ubuntu-latest
   steps:
     - name: first-step
       shell: bash
       run: echo "hello world from github"
     - name: Print to Log
       id: print-to-log
       uses: actions/hello-world-javascript-action@main
       with:
         who-to-greet: ${{ inputs.who-to-greet }}
     - name: print-time
       run: echo "the time of the greeting was ${{ steps.print-to-log.outputs.time }}"
 second-job:
   runs-on: ubuntu-latest
   needs: first-job
   env:
     JOB_VAR: "second job variable"
   steps:
     - name: step1
       env:
         STEP_VAR: "This variable is declared at the step level"
       shell: bash
       run: |
         echo "hello from step 2 after step 1"
         echo $WORKFLOW_VAR
         echo $JOB_VAR
         echo $STEP_VAR
         echo "The following is a secret: ${{ secrets.SOME_SECRET }}, of course, I cant tell you because then it wouldnt be a secret..."
         echo "The following are default environment variables:"
         echo $GITHUB_ACTOR
         echo $GITHUB_JOB
         echo $GITHUB_REF
               
